<a href="https://colab.research.google.com/github/Navjotkarkhal/TR-102-/blob/main/Day_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**


**Creation on numpy array**

In [2]:
import numpy as np

In [3]:
import numpy as np
l1=[1,2,3,4]
l2=[5,4,3,2]
l3=[1,2,3]
type(l1)

list

In [4]:
arr1= np.array(l1)
arr1

array([1, 2, 3, 4])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([l1,l2])
arr2

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [7]:

arr2.shape

(2, 4)

In [8]:
np.zeros(200)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

**Reshaping Arrays**

In [12]:
l=[1,2,3,4,5]

In [13]:
arr=np.arange(0,50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
arr.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [15]:
np.arange(20).reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

**Indexing**

In [16]:
random_arr=np.random.randint(1,101, size=(10,10))
random_arr

array([[ 8, 66, 80, 49, 54,  5, 34, 23, 33, 32],
       [30, 31, 54, 76, 35,  8, 44, 49, 62, 33],
       [48, 40, 91, 58, 99, 13,  8, 26, 51, 86],
       [ 1, 80, 39, 44, 74, 60, 38, 25, 33, 30],
       [73, 96, 70,  1, 95, 63, 74, 58, 50, 69],
       [14, 12, 86, 83, 42, 97,  4, 58, 60, 78],
       [23, 51, 27, 95, 96, 67, 24, 86, 62, 59],
       [57, 52, 43, 39, 25, 64, 66, 42, 84, 80],
       [78, 88, 47, 93, 45, 26,  9,  2, 63, 23],
       [70, 39, 38, 64, 56, 90,  8, 89, 11, 95]])

In [17]:
arr1

array([1, 2, 3, 4])

In [18]:
random_arr[0]

array([ 8, 66, 80, 49, 54,  5, 34, 23, 33, 32])

In [19]:
random_arr[3:8]

array([[ 1, 80, 39, 44, 74, 60, 38, 25, 33, 30],
       [73, 96, 70,  1, 95, 63, 74, 58, 50, 69],
       [14, 12, 86, 83, 42, 97,  4, 58, 60, 78],
       [23, 51, 27, 95, 96, 67, 24, 86, 62, 59],
       [57, 52, 43, 39, 25, 64, 66, 42, 84, 80]])

**Sorting Arrays**


In [20]:
unsorted_arr=np.array([30,20,40,2,10,50,60,5,80,90,70])
unsorted_arr

array([30, 20, 40,  2, 10, 50, 60,  5, 80, 90, 70])

In [24]:
sorted(unsorted_arr)

[2, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [23]:
unsorted_arr.sort()
unsorted_arr

array([ 2,  5, 10, 20, 30, 40, 50, 60, 70, 80, 90])

**Slicing**

In [26]:
sliced_arr=unsorted_arr[2:6]
sliced_arr

array([10, 20, 30, 40])

In [27]:

sliced_arr[0]=100

In [28]:
sliced_arr

array([100,  20,  30,  40])

In [29]:
new_arr=unsorted_arr.copy()
new_arr

array([  2,   5, 100,  20,  30,  40,  50,  60,  70,  80,  90])